---
- name: Converge
  hosts: all
  roles:
    - role: tangrama.motd
  vars:
    hostname: "localhost"
    motd_info:
      - " FQDN:    ": "{{ ansible_fqdn }}"
      - " Distro:  ": "{{ ansible_distribution }} {{ ansible_distribution_version }} {{ ansible_distribution_release }}"
      - " Virtual: ": "{{ 'YES' if ansible_virtualization_role == 'guest' else 'NO' }}\n"
      - " CPUs:    ": "{{ ansible_processor_vcpus }}"
      - " RAM:     ": "{{ (ansible_memtotal_mb / 1000) | round(1) }}GB"
      - " Service: ": "example.com"
